# neovim configs
set -sg escape-time 10
set -g focus-events on

# settings 
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",alacritty:RGB"

# turn mouse on
set -g mouse on
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# plugins
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'b0o/tmux-autoreload'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '~/.tmux/plugins/tpm/tpm'
