# bindings
bind-key -r r source-file ~/.tmux.conf

# Configs
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on
set -g status-position top
set -ag terminal-overrides ",alacritty:RGB"

# Tweak for vim escape slowness
set -sg escape-time 10

# Plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "catppuccin/tmux"

# Just use plugin manager
set-environment -g PATH "/opt/homebrew/bin:/bin:/usr/bin"
run "~/.tmux/plugins/tpm/tpm"
