return {
  diagnostics = {
    error = "",
    warn = "",
    hint = "",
    info = "",
  },
  git = {
    added = "",
    modified = "",
    removed = "",
    renamed = "R",
    untracked = "",
    ignored = "",
    unstaged = "U",
    staged = "",
    conflict = "",
  },
  gitsigns = {
    add = "┃",
    change = "┋",
    delete = "",
    topdelhfe = "",
    changedelete = "┃",
    untracked = "┃",
  },
  kinds = {
    Array = " ",
    Boolean = " ",
    Class = " ",
    Color = " ",
    Constant = " ",
    Constructor = " ",
    Copilot = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = " ",
    Interface = " ",
    Key = " ",
    Keyword = " ",
    Method = " ",
    Module = " ",
    Namespace = " ",
    Null = "ﳠ ",
    Number = " ",
    Object = " ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    String = " ",
    Struct = " ",
    Text = " ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = " ",
  },
  ui = {
    Pencil = "",
    Bug = "",
  },
}
